# Generated by Django 4.2.1 on 2023-05-31 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
